### ISSUE TITLE
Some tag values are type double but should be long

### ISSUE THREAD

**Issue by buma** [osmlab/osm-qa-tiles#5]
How is type of tags determined when encoding tiles with protocol buffer?
I used slovenia country extract and I see _osm_way_id, _version, _uid and timestamp as double value all those (except version) should probable be longs on.
I basically only see string values and double values. Even for example [admin_level](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#admin_level) is string and it could be int.

Example of problematic [way](http://www.openstreetmap.org/way/316408714).

I'm seeing this with [python decoder](https://github.com/mapzen/mapbox-vector-tile) and with my Cpp decoder from protobuf. Type is read from layer values but is double. (TAG 3, but should probably be TAG 4 int64).

I don't know if this is the problem in my parsing which I doubt since protobuf reader is generated from proto file or is there a problem in data.

**Comment by e-n-f** [comment]
The tiles are encoded by [tippecanoe](https://github.com/mapbox/tippecanoe), which doesn't distinguish between integer and floating point mostly because its input is GeoJSON, which doesn't distinguish between integer and floating point. You're right that it would be better to encode integer values as integers and I'll make that change.

I'm not sure why `admin_level` is encoded as a string but I suspect [minjur](https://github.com/mapbox/minjur) may output all OSM properties as strings since they aren't tagged with a type in `planet.osm`.

**Comment by e-n-f** [comment]
The tippecanoe side of the should be fixed in https://github.com/mapbox/tippecanoe/pull/125.

**Comment by buma** [comment]
That's great. Thanks for the quick fix. I'll test it tomorrow.
